version: '3'
services:
  bot:
    build: '.'
    image: registry.gitlab.com/lolpants/stream-role-bot:latest
    links:
    - redis
    env_file:
    - streambot.env
    restart: always
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
    - ./db:/data
    restart: always
